version: '3.9'

services:
  postgres:
    image: ${POSTGRES_IMAGE}
    networks:
      - book-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES=${POSTGRES_USER}
    ports:
      - ${POSTGRES_OUT_PORT}:${POSTGRES_INNER_PORT}
    container_name: postgres
  db-book:
    image: ${SERVER_IMAGE}
    environment:
      - POSTGRES_PASSWORD_SERVER=${POSTGRES_PASSWORD}
      - POSTGRES_PORT_SERVER=${POSTGRES_INNER_PORT}
      - POSTGRES_HOST_SERVER=${POSTGRES_HOST}
      - POSTGRES_USER_SERVER=${POSTGRES_USER}
      - POSTGRES_DB_NAME_SERVER=${POSTGRES_DB_NAME}
      - POSTGRES_SSLMODE_SERVER=${POSTGRES_SSLMODE}
    ports:
      - ${SERVER_OUT_PORT}:${SERVER_INNER_PORT}
    container_name: ${SERVER_CONTAINER_NAME}
    networks:
      - ${NETWORK_NAME}
    depends_on:
      - ${POSTGRES_NAME}

networks:
  book-network:
    name: ${NETWORK_NAME}
